apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: updatedemo-deployment
spec:
  replicas: 1 # just 1 pod
  template: 
    metadata:
      labels:
        app: updatedemo
    spec:
      containers:
      - name: updatedemo
        image: mgruc/updatedemo:v1
        ports:
        - containerPort: 8080